## Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://db:5432/modulo1db
spring.datasource.username=modulo1
spring.datasource.password=modulo1

# Cria ou atualiza o esquema automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Porta do servidor
server.port=8080

# Configuração do perfil ativo
spring.profiles.active=default